#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from genericdiff import *

def test_GenerifDiff_lt():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der < h.der)

def test_GenerifDiff_gt():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der > h.der)

def test_GenerifDiff_eq():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der == h.der)
 
def test_GenerifDiff_ne():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der != h.der)

def test_GenerifDiff_le():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der <= h.der)

def test_GenerifDiff_ge():
    f = GenericDiff(1, 0)
    h = 2
    assert (f.der >= h.der)